version: "3.8"
services:
  pcg_skeleton_api:
    container_name: "pcg_skeleton_api"
    image: "pcg_skeleton_api:latest"
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - fastapi-nano
    volumes:
        - .:/code
    ports:
      - 5000:5000
